# Based on https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml

name: Render and Publish

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::dplyr
            any::rmarkdown
            any::knitr
            any::DT
            any::BiocPkgTools

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      # Run `quarto publish gh-pages` once locally
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
